[package]
name = "libsql_generate"
version = "0.1.0"
edition = "2021"

[dependencies]
libsql_bindgen = "0"
magic-crypt = "3.1"
rand = "0"
getrandom = { version = "0", features = ["js"] }
serde = "1"
syn = "1"
itoa = "1"

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true
check-overflows = false
opt-level = "s"
